language: cpp

sudo: false

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build

script: make test
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then
      case ${BUILD} in
        gcc)
          cmake ../ &&
          make &&
          make test
          ;;
      esac ;
    fi

